# 私有库
source 'https://git.dev.tencent.com/Rogue24/JPSpecs.git'
# 公有库
source 'https://github.com/CocoaPods/Specs.git'

# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  
  pod 'JPBasic/JPCategory'
  pod 'JPBasic/JPTool'

end
